export const escapeRegex = (string: string): string => { return string.replace(/[.*+?^${}()|\[\]\\]/g, '\\$&') }
export const escapeHtml = (text: string): string => { if (!text) return ''; const map: Record<string, string> = { '&': '&amp;','<': '&lt;','>': '&gt;','"': '&quot;',"'": '&#039;' }; return text.replace(/[&<>'"]/g, m => map[m]) }
export function debounce<T extends (...args: any[]) => any>(fn: T, delay: number): (...args: Parameters<T>) => void { let timeoutId: ReturnType<typeof setTimeout>; return (...args: Parameters<T>) => { clearTimeout(timeoutId); timeoutId = setTimeout(() => fn(...args), delay) } }
export function throttle<T extends (...args: any[]) => any>(fn: T, limit: number): (...args: Parameters<T>) => void { let inThrottle: boolean; return (...args: Parameters<T>) => { if (!inThrottle) { fn(...args); inThrottle = true; setTimeout(() => (inThrottle = false), limit) } } }
export const formatTime = (time: number): string => { const minutes = Math.floor(time / 60); const seconds = Math.floor(time % 60); return `${minutes}:${seconds < 10 ? '0' : ''}${seconds}` }
export const highlightMatch = (text: string, query: string): string => { if (!text || !query) return escapeHtml(text); const escapedQuery = escapeRegex(query); const regex = new RegExp(`(${escapedQuery})`, 'gi'); return escapeHtml(text).replace(regex, '<mark style="background-color: rgba(255, 192, 203, 0.3); color: var(--common-color-1); padding: 0 2px; border-radius: 2px;">$1</mark>') }
export const generateId = (length: number = 8): string => { return Math.random().toString(36).substring(2, 2 + length) }
export function deepClone<T>(obj: T): T { if (obj === null || typeof obj !== 'object') return obj; if (obj instanceof Date) return new Date(obj.getTime()) as unknown as T; if (Array.isArray(obj)) return obj.map(item => deepClone(item)) as unknown as T; if (typeof obj === 'object') { const clonedObj: Record<string, any> = {}; for (const key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) { clonedObj[key] = deepClone((obj as Record<string, any>)[key]) } } return clonedObj as T } return obj }
export const isBrowser = (): boolean => { return typeof window !== 'undefined' && typeof document !== 'undefined' }
export function safeJsonParse<T = any>(jsonString: string, defaultValue: T | null = null): T | null { try { return JSON.parse(jsonString) } catch (error) { return defaultValue } }
export const storage = { get: <T = any>(key: string, defaultValue: T | null = null): T | null => { if (!isBrowser()) return defaultValue; try { const value = localStorage.getItem(key); return value ? safeJsonParse<T>(value, defaultValue) : defaultValue } catch (error) { return defaultValue } }, set: (key: string, value: any): boolean => { if (!isBrowser()) return false; try { localStorage.setItem(key, JSON.stringify(value)); return true } catch (error) { return false } }, remove: (key: string): boolean => { if (!isBrowser()) return false; try { localStorage.removeItem(key); return true } catch (error) { return false } }, clear: (): boolean => { if (!isBrowser()) return false; try { localStorage.clear(); return true } catch (error) { return false } } }
export const performance = { measure: <T>(name: string, fn: () => T): { result: T; duration: number } => { const start = performance.now(); const result = fn(); const duration = performance.now() - start; if (isBrowser() && (window as any).performanceMonitor?.recordMetric) { (window as any).performanceMonitor.recordMetric(name, duration) }; return { result, duration } }, start: (name: string): void => { if (!isBrowser()) return; if (!(window as any).performanceTimers) { (window as any).performanceTimers = {} }; (window as any).performanceTimers[name] = performance.now() }, end: (name: string): number | null => { if (!isBrowser()) return null; if (!(window as any).performanceTimers?.[name]) return null; const duration = performance.now() - (window as any).performanceTimers[name]; delete (window as any).performanceTimers[name]; if ((window as any).performanceMonitor?.recordMetric) { (window as any).performanceMonitor.recordMetric(name, duration) }; return duration } }
